package com.inventorymanagementsystem.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ExportPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.customer_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer merchandiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.original_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private BigDecimal originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.final_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private BigDecimal finalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.start_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.end_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.adding_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Date addingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.operator
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_price.remark
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ExportPrice(Integer id, Integer customerId, Integer merchandiseId, BigDecimal originalPrice, BigDecimal finalPrice, Date startTime, Date endTime, Date addingTime, String operator, String remark) {
        this.id = id;
        this.customerId = customerId;
        this.merchandiseId = merchandiseId;
        this.originalPrice = originalPrice;
        this.finalPrice = finalPrice;
        this.startTime = startTime;
        this.endTime = endTime;
        this.addingTime = addingTime;
        this.operator = operator;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ExportPrice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.id
     *
     * @return the value of export_price.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.id
     *
     * @param id the value for export_price.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.customer_id
     *
     * @return the value of export_price.customer_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.customer_id
     *
     * @param customerId the value for export_price.customer_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.merchandise_id
     *
     * @return the value of export_price.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.merchandise_id
     *
     * @param merchandiseId the value for export_price.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMerchandiseId(Integer merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.original_price
     *
     * @return the value of export_price.original_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.original_price
     *
     * @param originalPrice the value for export_price.original_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.final_price
     *
     * @return the value of export_price.final_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public BigDecimal getFinalPrice() {
        return finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.final_price
     *
     * @param finalPrice the value for export_price.final_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setFinalPrice(BigDecimal finalPrice) {
        this.finalPrice = finalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.start_time
     *
     * @return the value of export_price.start_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.start_time
     *
     * @param startTime the value for export_price.start_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.end_time
     *
     * @return the value of export_price.end_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.end_time
     *
     * @param endTime the value for export_price.end_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.adding_time
     *
     * @return the value of export_price.adding_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Date getAddingTime() {
        return addingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.adding_time
     *
     * @param addingTime the value for export_price.adding_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setAddingTime(Date addingTime) {
        this.addingTime = addingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.operator
     *
     * @return the value of export_price.operator
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.operator
     *
     * @param operator the value for export_price.operator
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_price.remark
     *
     * @return the value of export_price.remark
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_price.remark
     *
     * @param remark the value for export_price.remark
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}