package com.inventorymanagementsystem.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ExportMonthStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.customer_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer merchandiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.accounts_receivable
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private BigDecimal accountsReceivable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.if_received
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Boolean ifReceived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_month_statistics.receive_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Date receiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ExportMonthStatistics(Integer id, String year, String month, Integer customerId, Integer merchandiseId, Integer typeId, BigDecimal accountsReceivable, Boolean ifReceived, Date receiveTime) {
        this.id = id;
        this.year = year;
        this.month = month;
        this.customerId = customerId;
        this.merchandiseId = merchandiseId;
        this.typeId = typeId;
        this.accountsReceivable = accountsReceivable;
        this.ifReceived = ifReceived;
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ExportMonthStatistics() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.id
     *
     * @return the value of export_month_statistics.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.id
     *
     * @param id the value for export_month_statistics.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.year
     *
     * @return the value of export_month_statistics.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.year
     *
     * @param year the value for export_month_statistics.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.month
     *
     * @return the value of export_month_statistics.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.month
     *
     * @param month the value for export_month_statistics.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.customer_id
     *
     * @return the value of export_month_statistics.customer_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.customer_id
     *
     * @param customerId the value for export_month_statistics.customer_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.merchandise_id
     *
     * @return the value of export_month_statistics.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.merchandise_id
     *
     * @param merchandiseId the value for export_month_statistics.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMerchandiseId(Integer merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.type_id
     *
     * @return the value of export_month_statistics.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.type_id
     *
     * @param typeId the value for export_month_statistics.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.accounts_receivable
     *
     * @return the value of export_month_statistics.accounts_receivable
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public BigDecimal getAccountsReceivable() {
        return accountsReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.accounts_receivable
     *
     * @param accountsReceivable the value for export_month_statistics.accounts_receivable
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setAccountsReceivable(BigDecimal accountsReceivable) {
        this.accountsReceivable = accountsReceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.if_received
     *
     * @return the value of export_month_statistics.if_received
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Boolean getIfReceived() {
        return ifReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.if_received
     *
     * @param ifReceived the value for export_month_statistics.if_received
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setIfReceived(Boolean ifReceived) {
        this.ifReceived = ifReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_month_statistics.receive_time
     *
     * @return the value of export_month_statistics.receive_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_month_statistics.receive_time
     *
     * @param receiveTime the value for export_month_statistics.receive_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }
}