package com.inventorymanagementsystem.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ImportMonthStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.supplier_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer merchandiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.accounts_payable
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private BigDecimal accountsPayable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.if_paid
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Boolean ifPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.paid_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Date paidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.inventory_amount
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer inventoryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_month_statistics.inventory_money
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private BigDecimal inventoryMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ImportMonthStatistics(Integer id, String year, String month, Integer supplierId, Integer merchandiseId, Integer typeId, BigDecimal accountsPayable, Boolean ifPaid, Date paidTime, Integer inventoryAmount, BigDecimal inventoryMoney) {
        this.id = id;
        this.year = year;
        this.month = month;
        this.supplierId = supplierId;
        this.merchandiseId = merchandiseId;
        this.typeId = typeId;
        this.accountsPayable = accountsPayable;
        this.ifPaid = ifPaid;
        this.paidTime = paidTime;
        this.inventoryAmount = inventoryAmount;
        this.inventoryMoney = inventoryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ImportMonthStatistics() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.id
     *
     * @return the value of import_month_statistics.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.id
     *
     * @param id the value for import_month_statistics.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.year
     *
     * @return the value of import_month_statistics.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.year
     *
     * @param year the value for import_month_statistics.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.month
     *
     * @return the value of import_month_statistics.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.month
     *
     * @param month the value for import_month_statistics.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.supplier_id
     *
     * @return the value of import_month_statistics.supplier_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.supplier_id
     *
     * @param supplierId the value for import_month_statistics.supplier_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.merchandise_id
     *
     * @return the value of import_month_statistics.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.merchandise_id
     *
     * @param merchandiseId the value for import_month_statistics.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMerchandiseId(Integer merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.type_id
     *
     * @return the value of import_month_statistics.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.type_id
     *
     * @param typeId the value for import_month_statistics.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.accounts_payable
     *
     * @return the value of import_month_statistics.accounts_payable
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public BigDecimal getAccountsPayable() {
        return accountsPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.accounts_payable
     *
     * @param accountsPayable the value for import_month_statistics.accounts_payable
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setAccountsPayable(BigDecimal accountsPayable) {
        this.accountsPayable = accountsPayable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.if_paid
     *
     * @return the value of import_month_statistics.if_paid
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Boolean getIfPaid() {
        return ifPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.if_paid
     *
     * @param ifPaid the value for import_month_statistics.if_paid
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setIfPaid(Boolean ifPaid) {
        this.ifPaid = ifPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.paid_time
     *
     * @return the value of import_month_statistics.paid_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.paid_time
     *
     * @param paidTime the value for import_month_statistics.paid_time
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.inventory_amount
     *
     * @return the value of import_month_statistics.inventory_amount
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getInventoryAmount() {
        return inventoryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.inventory_amount
     *
     * @param inventoryAmount the value for import_month_statistics.inventory_amount
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setInventoryAmount(Integer inventoryAmount) {
        this.inventoryAmount = inventoryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_month_statistics.inventory_money
     *
     * @return the value of import_month_statistics.inventory_money
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public BigDecimal getInventoryMoney() {
        return inventoryMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_month_statistics.inventory_money
     *
     * @param inventoryMoney the value for import_month_statistics.inventory_money
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setInventoryMoney(BigDecimal inventoryMoney) {
        this.inventoryMoney = inventoryMoney;
    }
}