package com.inventorymanagementsystem.entity;

import java.math.BigDecimal;

public class ImportBill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.bill_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.merchandise_typeId
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer merchandiseTypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer merchandiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.supplier_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.amount
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.day
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.operator
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_bill.remark
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ImportBill(Integer id, Integer billId, Integer merchandiseTypeid, Integer merchandiseId, Integer supplierId, Integer amount, BigDecimal price, String year, String month, String day, String operator, String remark) {
        this.id = id;
        this.billId = billId;
        this.merchandiseTypeid = merchandiseTypeid;
        this.merchandiseId = merchandiseId;
        this.supplierId = supplierId;
        this.amount = amount;
        this.price = price;
        this.year = year;
        this.month = month;
        this.day = day;
        this.operator = operator;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public ImportBill() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.id
     *
     * @return the value of import_bill.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.id
     *
     * @param id the value for import_bill.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.bill_id
     *
     * @return the value of import_bill.bill_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.bill_id
     *
     * @param billId the value for import_bill.bill_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.merchandise_typeId
     *
     * @return the value of import_bill.merchandise_typeId
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getMerchandiseTypeid() {
        return merchandiseTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.merchandise_typeId
     *
     * @param merchandiseTypeid the value for import_bill.merchandise_typeId
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMerchandiseTypeid(Integer merchandiseTypeid) {
        this.merchandiseTypeid = merchandiseTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.merchandise_id
     *
     * @return the value of import_bill.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getMerchandiseId() {
        return merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.merchandise_id
     *
     * @param merchandiseId the value for import_bill.merchandise_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMerchandiseId(Integer merchandiseId) {
        this.merchandiseId = merchandiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.supplier_id
     *
     * @return the value of import_bill.supplier_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.supplier_id
     *
     * @param supplierId the value for import_bill.supplier_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.amount
     *
     * @return the value of import_bill.amount
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.amount
     *
     * @param amount the value for import_bill.amount
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.price
     *
     * @return the value of import_bill.price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.price
     *
     * @param price the value for import_bill.price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.year
     *
     * @return the value of import_bill.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.year
     *
     * @param year the value for import_bill.year
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.month
     *
     * @return the value of import_bill.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.month
     *
     * @param month the value for import_bill.month
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.day
     *
     * @return the value of import_bill.day
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.day
     *
     * @param day the value for import_bill.day
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.operator
     *
     * @return the value of import_bill.operator
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.operator
     *
     * @param operator the value for import_bill.operator
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_bill.remark
     *
     * @return the value of import_bill.remark
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_bill.remark
     *
     * @param remark the value for import_bill.remark
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}