package com.inventorymanagementsystem.entity;

public class Merchandise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandise.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandise.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandise.name
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandise.type_name
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandise.unit
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchandise.specification
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    private String specification;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Merchandise(Integer id, Integer typeId, String name, String typeName, String unit, String specification) {
        this.id = id;
        this.typeId = typeId;
        this.name = name;
        this.typeName = typeName;
        this.unit = unit;
        this.specification = specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Merchandise() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandise.id
     *
     * @return the value of merchandise.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandise.id
     *
     * @param id the value for merchandise.id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandise.type_id
     *
     * @return the value of merchandise.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandise.type_id
     *
     * @param typeId the value for merchandise.type_id
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandise.name
     *
     * @return the value of merchandise.name
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandise.name
     *
     * @param name the value for merchandise.name
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandise.type_name
     *
     * @return the value of merchandise.type_name
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandise.type_name
     *
     * @param typeName the value for merchandise.type_name
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandise.unit
     *
     * @return the value of merchandise.unit
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandise.unit
     *
     * @param unit the value for merchandise.unit
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchandise.specification
     *
     * @return the value of merchandise.specification
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchandise.specification
     *
     * @param specification the value for merchandise.specification
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    public void setSpecification(String specification) {
        this.specification = specification == null ? null : specification.trim();
    }
}