package com.inventorymanagementsystem.mapper;

import com.inventorymanagementsystem.entity.ExportMonthStatistics;

public interface ExportMonthStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insert(ExportMonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insertSelective(ExportMonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    ExportMonthStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ExportMonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKey(ExportMonthStatistics record);
}