package com.inventorymanagementsystem.mapper;

import com.inventorymanagementsystem.entity.ExportPrice;

public interface ExportPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insert(ExportPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insertSelective(ExportPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    ExportPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ExportPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_price
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKey(ExportPrice record);
}