package com.inventorymanagementsystem.mapper;

import com.inventorymanagementsystem.entity.ImportMonthStatistics;

public interface ImportMonthStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insert(ImportMonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insertSelective(ImportMonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    ImportMonthStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ImportMonthStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_month_statistics
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKey(ImportMonthStatistics record);
}