package com.inventorymanagementsystem.mapper;

import com.inventorymanagementsystem.entity.ImportBill;

public interface ImportBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insert(ImportBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insertSelective(ImportBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    ImportBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ImportBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_bill
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKey(ImportBill record);
}