package com.inventorymanagementsystem.mapper;

import com.inventorymanagementsystem.entity.MerchandiseType;

public interface MerchandiseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise_type
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise_type
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insert(MerchandiseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise_type
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insertSelective(MerchandiseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise_type
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    MerchandiseType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise_type
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(MerchandiseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchandise_type
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKey(MerchandiseType record);
}