package com.inventorymanagementsystem.mapper;

import com.inventorymanagementsystem.entity.Supplier;

public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    Supplier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Tue May 11 09:42:29 GMT+08:00 2021
     */
    int updateByPrimaryKey(Supplier record);
}